name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  patch_version:
    runs-on: ubuntu-latest

    steps:
    
    # Checks-out to $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      name: Checkout source
      
    - id: get_chromedriver_version
      name: Get current ChromeDriver version
      run: |
        content=$(wget https://chromedriver.storage.googleapis.com/LATEST_RELEASE -q -O -)
        echo $content
        echo ::set-env name=CHROME_VERSION::$content
        sed -i -E "s/R: (.*)/R: $content/g" appveyor.yml
        
    - uses: stefanzweifel/git-auto-commit-action@v4
      name: Commit to repository
      with:
          commit_message: Version $CHROME_VERSION
    

