name: check and update chromedriver version

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  patch_version:
    runs-on: ubuntu-latest

    steps:
    
    # Avoids the scheduled job being disabled after 60 days of inactivity to the repo
    - uses: gautamkrishnar/keepalive-workflow@v1 
    
    - uses: actions/checkout@v2
      name: Checkout source
    
    # Parse the current chrome version from Google
    - id: get_chromedriver_version
      name: Get current ChromeDriver version
      run: |
        chromeVersion=$(wget https://chromedriver.storage.googleapis.com/LATEST_RELEASE -q -O -)
        echo $chromeVersion
        sed -i -E "s/R: (.*)/R: $chromeVersion/g" appveyor.yml
        echo "version=$chromeVersion" >> "$GITHUB_OUTPUT"
        
    - uses: stefanzweifel/git-auto-commit-action@v4
      name: Commit to repository
      with:
          commit_message: Version ${{ steps.get_chromedriver_version.outputs.version }}
    

